/* eslint-disable no-unused-vars */

export enum WeatherCodesEnum {
    'clear-sky' = 0,
    'mainly-clear' = 1,
    'partly-cloudy' = 2,
    'overcast' = 3,
    'fog' = 45,
    'rime' = 48,
    'drizzle-light' = 51,
    'drizzle-moderate' = 53,
    'drizzle-dense' = 55,
    'freezing-light' = 56,
    'freezing-dense ' = 57,
    'rain-slight' = 61,
    'rain-moderate' = 63,
    'rain-heavy' = 65,
    'freezing-rain-light' = 66,
    'freezing-rain-heavy' = 67,
    'snow-fall-slight' = 71,
    'snow-fall-moderate' = 73,
    'snow-fall-heavy' = 75,
    'snow-grains' = 77,
    'rain-showers-slight' = 80,
    'rain-showers-moderate' = 81,
    'rain-showers-violent' = 82,
    'snow-showers-light' = 85,
    'snow-showers-heavy' = 86,
    'thunderstorm-slight-or-moderate' = 95,
    'thunderstorm-slight-hail' = 96,
    'thunderstorm-heavy-hail' = 99,
}
